name: Extract ZIP

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract ZIP
        run: |
          unzip Face-Recognition-Attendance-System-main.zip -d extracted
